### ISSUE TITLE
hook写法的建议

### ISSUE THREAD

**Issue by wjy000** [rk700/YAHFA#10]
希望可以像xposed那样有before after,并把参数方法封装回调,目前hook一个方法写一个类的写法太繁琐了

**Comment by rk700** [comment]
`hook()`方法中在调用`origin()`之前的和之后的代码，自然对应于xposed的before和after

YAHFA主要是做代码替换和备份，如果需要修改hook写法，可根据自己的需求实现，最终调用到`findAndBackupAndHook()`完成hook即可
