### ISSUE TITLE
Nested classes and interfaces

### ISSUE THREAD

**Issue by chritsian** [rk700/YAHFA#106]
Hello,

I'm trying to hook methods which expect a nested interface as parameter. For example the takePicutre method (https://bit.ly/2u5VHIX).  Every time I get the error "YAHFA-Native: Cannot find target non-static method: ...."
Is there a specific way to declare nested interfaces or is it just impossible to do this with YAHFA?

Kind regards
Christian

**Comment by C3C0** [comment]
Nested classes and interfaces are referenced the same way as normal classes. In your particular case you should simply use Camera.ShutterCallback.class , ... ...

**Comment by chritsian** [comment]
Thanks for your quick response.
Unfortunately this don't work for me. I tried it with the .class extension too and also with and without package (android/hardware). None of these cases work. Here my code:

` public static String className = "android.hardware.Camera";
    public static String methodName = "takePicture";
    public static String methodSig = "(Landroid/hardware/Camera.ShutterCallback;Landroid/hardware/Camera.PictureCallback;" +
            "Landroid/hardware/Camera.PictureCallback;Landroid/hardware/Camera.PictureCallback;)V";`

What's my mistake?

**Comment by C3C0** [comment]
Did your try Landroid/hardware/Camera/ShutterCallback; (slash  instead of dot)

**Comment by chritsian** [comment]
Yes, but it didn't worked. I get the same problem with other methods too, like setPreviewDisplay. That's why I assume that there is a problem with nested interfaces or I didn't find out how to declare it correctly.

**Comment by solohsu** [comment]
@chritsian You should use a dollar sign for inner classes, e.g. `Camera$ShutterCallback`.

**Comment by C3C0** [comment]
Using . or $ makes no difference for me. At least when referencing classes the standard way, not smali type signatures.

**Comment by solohsu** [comment]
@C3C0 Yes. Here a smali type signature is needed since it's used to find the corresponding method using JNI function `GetMethodId`.

**Comment by chritsian** [comment]
@solohsu Thank you very much. It works now.
