### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by wjy000** [rk700/YAHFA#11]
大神你好
我修改了一点点你的hook插件的写法,你原先是反射静态变量获得类名等等,现在改成了反射hookMethods 方法,并且一个类下面可以hook多个方法,这种写法可以成功hook的
但是我遇到了一个困难,我想把所有hook的参数都放到hook (Object thiz, Object[] params)的params里面,不想准确的定义每一种参数类型,请问我要怎么做呢?
public class Hook_Test extends BaseHook
{
    @Override
    public String hookMethods ()
    {
        return methodsToStr(
                new HookMethod("zpp.wjy.testxvirtual.Test", "test"),//public String test ()
                new HookMethod("zpp.wjy.testxvirtual.Test", "test1")//public String test1 (String param1)
        );
    }
    public static String hook (Object thiz, Object[] params)
    {
        Log.i("hook", "hook到了" + thiz + " " + params.length);
        return "被hook了";
    }
    public static String origin ()
    {
        return "";
    }
}

**Comment by rk700** [comment]
可以根据自己的需求实现hook的加载，参数传递可以参考xposed的实现方式
