### ISSUE TITLE
关于原函数调用的问题

### ISSUE THREAD

**Issue by wjy000** [rk700/YAHFA#13]
public static boolean hook(String thiz, String prefix) {
        Log.w("YAHFA", "in String.startsWith(): "+thiz+", "+prefix);
        return origin(thiz, prefix);
    }

    public static boolean origin(String thiz, String prefix) {
        Log.w("YAHFA", "String.startsWith() should not be here");
        return false;
    }

这2个方法都会修改返回值,请问如果能得到方法本身的返回值呢?

**Comment by 16368728** [comment]
我也有这个问题，急需请教

**Comment by rk700** [comment]
@16368728 `()Ljava/util/List`少个分号：`()Ljava/util/List;`

**Comment by rk700** [comment]
`origin()`方法的具体实现是不需要考虑的，在hook时会把目标方法复制到`origin()`中，所以调用`origin()`就相当于调用hook之前的原方法

**Comment by 16368728** [comment]
您好，不好意思刚才犯了个低级错误，分号忘记少了。不过又回到了我昨天的问题上。
-----
    public static String className = "android.net.wifi.WifiManager";
    public static String methodName = "getScanResults";
    public static String methodSig = "()Ljava/util/List;";
    public static Object hook(Object thiz) {
        Log.i("YAHFA", "WifiManager getScanResults hooked");
        List<ScanResult> scanResults=((WifiManager)thiz).getScanResults();//搜索到的设备列表
        for (ScanResult scanResult : scanResults) {
            Log.w("--------------", scanResult.SSID);  //我希望在这里能够去掉一些，wifi列表，然后再返回
        }
        return scanResults;
    }
我这么获取不确定是否正确，但是执行之后无限循环，一直到资源耗尽。请教这个地方我应该如何操作？

**Comment by wjy000** [comment]
那应该如果写origin方法?origin方法的返回值也是我们自己定义的,本人比较菜,大神指点指点

**Comment by 16368728** [comment]
@wjy000 ，你的意思是写到 origin 方法中？可以试试看，怎么写都让人感觉有点怪怪的。

**Comment by wjy000** [comment]
我的意思是origin方法也是我们自己定义的返回值,如果调用才能得到原函数的返回值呢

**Comment by 16368728** [comment]
@wjy000 我没想明白在这个地方怎么用。我目的是要取出来，删除一些的wifi信息，再返回。

**Comment by rk700** [comment]
调用原方法造成循环，见https://github.com/rk700/YAHFA/issues/4

简单示例：

```java
public static Object hook(Object thiz) {
    Log.i("YAHFA", "WifiManager getScanResults hooked");
    List<ScanResult> scanResults=(List<ScanResult>)origin(thiz);
    for (ScanResult scanResult : scanResults) {
        Log.w("--------------", scanResult.SSID);
    }
    return scanResults;
}
public static Object origin (Object thiz) {
    return null;
}
```

**Comment by wjy000** [comment]
我终于知道了,原来hook origin 必须是静态方法,由于我继承的是baseHook,并没有使用静态方法,所有origin返回值总是错误

**Comment by 16368728** [comment]
@rk700 非常感谢，我终于知道怎么使用了。同时感谢 @wjy000  开贴。

**Comment by wjy000** [comment]
你搞定了,我还剩一个问题,我没办法hook 到application对象,大神嫌我水平低了,哈哈哈哈

**Comment by wjy000** [comment]
@rk700 对了,看你说写参数描述的时候忘记了写分号,写这个的确非常容易出错,特别是参数多的时候,不细心不行,不过我通过反射根据类名和方法名称自动生成这个描述,不需要自己写,如果你需要我可以发你

**Comment by 16368728** [comment]
@wjy000 尴尬了，还是不行。现在没搞明白 origin 中还需要怎么实现。按老大的说法，origin 是一个数据拷贝，那么就不用在实现了。但是怎么返回？应该返回什么？
