### ISSUE TITLE
关于hook重写类的问题

### ISSUE THREAD

**Issue by wjy000** [rk700/YAHFA#14]
yahfa指定类名和方法名称和参数字符串就可以完成hook,但是比如需要Hook Application对象的onCreate方法,但是Application对象可能会被重写,无法指定类名,如果在xposed中的话,可以通过反射得到onCreate方法,然后直接hook这个方法,不知道这种情况在yahfa中怎么解决呢?

**Comment by rk700** [comment]
这个没有办法，如果hook的目标不确定，那么用yahfa没办法做hook
