### ISSUE TITLE
无法hook反射调用

### ISSUE THREAD

**Issue by wjy000** [rk700/YAHFA#15]
用xposed hook住一个方法,即使用反射调用这个方法也可以照样修改,
但是用yahfa的话,反射调用就绕过了hook,对于反射调用yahfa有做处理吗?

**Comment by rk700** [comment]
理论上讲通过反射得到的是可以被hook的，实际可以试一下

**Comment by wjy000** [comment]
可以hook反射,不好意思,是我没仔细测试,
