### ISSUE TITLE
一个奇怪的问题

### ISSUE THREAD

**Issue by wjy000** [rk700/YAHFA#17]
public static void origin (Object thiz, String path)
    {
        //Log(thisClass(),"调用原函数");
    }
这是hook file类构造函数,我发现如果原函数下面不写任何东西在5.1系统就会崩溃,6.0系统正常,我猜想可能是没有写任何内容导致调用原函数失败,所以必须把这行注释解开才行,这个问题找的我头都大了

**Comment by rk700** [comment]
如果没有任何内容的方法，在编译时会优化为内联，从而造成hook失败

**Comment by wjy000** [comment]
看来只能增加一些无用代码了
