### ISSUE TITLE
我对您的框架进行了一些修复和实现x86_64,arm64

### ISSUE THREAD

**Issue by zhuotong** [rk700/YAHFA#20]
我对您的框架进行了一些修复和实现x86_64,arm64。

另外希望参与到项目中，一起对7.0以上系统进行解决

**Comment by rk700** [comment]
欢迎提PR~

现在Android N上已知的问题是垃圾回收时崩溃： https://github.com/rk700/YAHFA/issues/8

**Comment by zhuotong** [comment]
能留个联系方式吗？有几个问题想请教下

**Comment by rk700** [comment]
企鹅：2四2三2九五2八三
