### ISSUE TITLE
用的作者的virtualhook,  当HOOK的方法的返回值为void时，调用origin会导致程序“崩溃”

### ISSUE THREAD

**Issue by ws15621066586** [rk700/YAHFA#25]
public static String className = "android.view.View";
    public static String methodName = "setOnClickListener";
    public static String methodSig = "(Landroid/view/View$OnClickListener;)V";
    public void  hook(Object thiz, View.OnClickListener listener) {
      //  origin(thiz,listener)
        return ;
    }

    public static void origin(Object thiz,View.OnClickListener listener) {
        return ;
    }

**Comment by ws15621066586** [comment]
调试了一天，以为我的问题！，，最后排除到这问题，，急求解

**Comment by rk700** [comment]
hook()方法是static的，你忘了写了。在Android 6.0上实验没有遇到问题，以下是代码

```java
public class Hook_View_setOnClickListener {
    public static String className = "android.view.View";
    public static String methodName = "setOnClickListener";
    public static String methodSig = "(Landroid/view/View$OnClickListener;)V";
    public static void hook(Object thiz, View.OnClickListener listener) {
        origin(thiz, listener);
        Log.w("YAHFA", "setOnClickListener called on View: "+thiz);
        return ;
    }

    public static void origin(Object thiz,View.OnClickListener listener) {
        Log.w("YAHFA", "should not be here");
        return ;
    }
}
```

另外，origin()方法建议不要为空，在某些版本上由于编译优化，会将其内联掉。见#17
