### ISSUE TITLE
把issue全看了，还是没能搞明白origin和hook的作用

### ISSUE THREAD

**Issue by netstu** [rk700/YAHFA#32]
1.有一个issue中说到 origin 和 hook可以做到 xposed中的before和after，但具体如何做？

2. origin具体是干嘛的？为什么有的例子中有，有的没有？

3. origin的返回值是随便写都没有关系吗？

4. origin 和 hook 都必须定义为 static ，那么返回值呢？是不是不能随便定义？

5. 如果实现xposed中的 param.getResult和param.setResult的功能？

麻烦了，谢谢

**Comment by svengong** [comment]
2 origin是调用原函数用的
3 origin的返回值，按你的需要写，只要不出错
