### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by netstu** [rk700/YAHFA#34]
10-20 04:50:34.749: W/ActivityManager(1224):   Force finishing activity 1 io.virtualhook/com.lody.virtual.client.stub.StubActivity$C0
10-20 04:50:34.789: W/art(1224): Suspending all threads took: 12.479ms
10-20 04:50:34.842: W/ActivityManager(1224): finishTopRunningActivityLocked , taskNdx is 45, activityNdx is 0
10-20 04:50:34.967: W/MediaFocusControl(1224):   AudioFocus   audio focus client died
10-20 04:50:34.970: W/ActivityManager(1224): getRecentTasks: caller 10099 does not hold REAL_GET_TASKS; limiting output
10-20 04:50:34.985: W/ADB_SERVICES(403): terminating JDWP 26680 connection: Try again
10-20 04:50:35.040: W/InputMethodManagerService(1224): Got RemoteException sending setActive(false) notification to pid 26680 uid 10099
10-20 04:50:35.047: W/ActivityManager(1224): getRunningAppProcesses: caller 10094 does not hold REAL_GET_TASKS; limiting output
10-20 04:50:35.068: W/PerfScheduler(1224): Not Boost !
10-20 04:50:35.312: W/ActivityManager(1224): getRunningAppProcesses: caller 1001 is using old GET_TASKS but privileged; allowing
10-20 04:50:35.315: E/CellLocation(2746): create GsmCellLocation
10-20 04:50:38.624: W/ActivityManager(1224): getRunningAppProcesses: caller 10102 does not hold REAL_GET_TASKS; limiting output

**Comment by svengong** [comment]
你这么提问题，谁都帮不了你
