### ISSUE TITLE
origin返回什么值？

### ISSUE THREAD

**Issue by netstu** [rk700/YAHFA#35]
其中一个issue中提到按实际hook的方法进行返回,这些我基本知道怎么回事了，即，原方法返回值是什么类型，则hook返回什么类型

我现在想问的是，
例子中返回值类型为void的，都是直接return
,返回值是String的有的反回null或""

一。origin中的返回质到底有什么用？是随意写吗，有什么影响呢？影响什么？

二。hook,origin,原函数 这几个执行的流程是什么？我大概知道一些，但还是有些不太清楚

**Comment by svengong** [comment]
一，如果不理解原理，保持类型一致即可，值任意
二，如果不理解art函数调用的逻辑，讲不清楚

**Comment by netstu** [comment]
我不了解，所以问问啊，给点关键词或者链接我自己查一下

**Comment by rk700** [comment]
1. origin返回值任意，只要origin方法签名正确，能够编译通过即可
2. hook()调用origin()，origin()被替换为原方法

**Comment by netstu** [comment]
@rk700 谢谢

最近写了一部分，看了好多例子，也有些理解了。我再描述一下我的理解，你帮我看一下是否正确？

hook()方法写自己的逻辑，在Hook()方法中可以调用origin()，也可以不调用（或者说可以不写origin），如果不调用，则原app中的原方法不会执行。在hook中的任何地方调用origin()方法，则表示此时执行了原app中的原方法。比如：

String hook(Object thiz, String param) {
  Log.d(tag, "aa");

  param = "修改param";
  String ret = origin(thiz, param);
  Log.d(tag, "bb");

  if(ret == "特定值") {
     ret = "xxretval";
  } 

   return ret;
}

则表示先执行aa,再执行原方法，再执行bb.其实也类似于xposed中的before和after了

如果要修改结果或者改变参数，可以在origin执行前后进行修改，这样理解对吧？
