### ISSUE TITLE
如何得到lab.galaxy.yahfa.HookInfo所在的app的context

### ISSUE THREAD

**Issue by netstu** [rk700/YAHFA#37]
我想写个配置界面，保存于sharedprefences，在hook()中如何读取得到？

**Comment by rk700** [comment]
可在`Application.onCreate()`处下hook

**Comment by rk700** [comment]
如果注入点在Application创建之后，可以在某个`Activity.onCreate()`处下hook

**Comment by svengong** [comment]
也可以在Application的attachBaseContext处hook，看个人喜好

**Comment by netstu** [comment]
谢谢 @rk700 @svengong 我试试吧，可能你们的模式和我说的不是一个意思。

比如我要hook的app为Aapp，我自己写的插件为Bapp,那么我为Bapp写一个界面，想在hook()中获取Bapp的context。

我现在用了另一个办法，直接写json文件
