### ISSUE TITLE
使用方法存在多级级联时遇到问题。

### ISSUE THREAD

**Issue by lizhanping** [rk700/YAHFA#4]
我想hook 访问SDCard时的一些常用操作所涉及的方法，如getExternalStorageState()时，遇到这种使用
Environment.getExternalStorageState().equals(Environment.MEDIA_MOUNTED
)时，为什么hook不到中间的getExternalStorageState()方法？
而如果单独使用string temp=Environment.getExternalStorageState()是可以的。

**Comment by rk700** [comment]
我在一台5.0和6.0的设备上试验，未能复现。

方法hook不住，主要与dex2oat的编译有关，例如方法被编译成为inline的，或者没有PIC直接跳转到编译时确定的入口。所以这类问题应该与设备和系统关系较大。

可以提供下oatdump得到的方法编译得到的机器码，看一下`getExternalStorageState()`是如何执行的

**Comment by lizhanping** [comment]
感谢答复，问题原因找到了，是我粗心在YAHFA中将methodSig赋值写错了，应该是Ljava/lang/String,由于拷贝未检查，误写成Ljava/io/String所导致未能hook到。。

现在有个奇怪的情况，就是如果我在hook中使用了被hook的方法，就会陷入死循环从而应用挂掉了。比如一个apk有个写sdcard的操作，我hook到这个操作，则使用相同的方式去写日志文件至sdcard，这样貌似会导致死循环，是否有解决的办法？
本人新入门菜鸟，如果有什么问的不对，还请包涵。

**Comment by rk700** [comment]
如果需要在`hook()`执行原方法，不要通过直接调用原方法的方式完成，这样肯定会陷入死循环的。正确的做法是调用`origin()`方法，`origin()`备份了进行hook之前方法内容。具体可参考demo
