### ISSUE TITLE
奔溃  android 8.0 oneplus 5

### ISSUE THREAD

**Issue by Code89757** [rk700/YAHFA#56]
06-05 18:50:21.345 19595-19595/lab.galaxy.yahfa.demoApp A/libc: Fatal signal 7 (SIGBUS), code 1, fault addr 0x1e14e000000003 in tid 19595 (y.yahfa.demoApp), pid 19595 (y.yahfa.demoApp)

**Comment by Code89757** [comment]
File：trampoline.c
Line:129
`
 switch (SDKVersion) {
        case ANDROID_O:
            trampoline1[13] = '\x14'; //10 14 40 f9 ; ldr x16, [x0, #40]
            break;
....
}
`
是否应该修改一下，比如：
`
    switch (SDKVersion) {
        case ANDROID_O2:
        case ANDROID_O:
            trampoline1[13] = '\x14'; //10 14 40 f9 ; ldr x16, [x0, #40]
            break;
`

**Comment by rk700** [comment]
已合并 https://github.com/rk700/YAHFA/pull/57
