### ISSUE TITLE
如何HOOK动态加载DEX？

### ISSUE THREAD

**Issue by koangel** [rk700/YAHFA#59]
我试了HOOK几个加密的AES函数是动态加载的外部插件，多次加载的，如何HOOK？

**Comment by rk700** [comment]
那只能在这些插件加载完成后再调用hook，否则找不到目标

**Comment by koangel** [comment]
已解决，HOOK DEXCLASSLOADER就好了，取到就随便HOOK了，做了个异步HOOK
