### ISSUE TITLE
hook failed

### ISSUE THREAD

**Issue by rrrfff** [rk700/YAHFA#6]
在genymotion android 5.0.0上hook没成功,
findAndBackupAndHook(targetClass, methodName, methodSig, hook, backup)显示done,
但是调用methodName所代表的方法依然是原来的方法, 调用backup所代表的方法会跳到methodName所代表的方法,
说明backup成功, hook失败了.

还未深究源码先贴这

**Comment by rk700** [comment]
hook的目标是什么？通过oatdump打印下调用目标方法的相关代码对应的机器指令呢？

hook失败，基本上是因为目标方法在执行时没有通过entrypoint这种间接寻址的方式跳转，而是直接调用目标方法了

**Comment by rrrfff** [comment]
原先目标是ContextWrapper.getPackageInfo, 没成功,findAndBackupAndHook后调用ContextWrapper.getPackageInfo还是进到系统方法, 后来用自己定义的类也不成功.
换了份hook代码就成功了https://github.com/Lerist/epic

**Comment by rrrfff** [comment]
因为现在没在做这个, 暂时没办法提供更详细的信息了
