### ISSUE TITLE
is there any way I can know who is calling the hook function?

### ISSUE THREAD

**Issue by zillions** [rk700/YAHFA#64]
Hi, Great Work.
Played around a bit, really good job, a question:
is there a way I can know who is calling the hook function? Like uid or packagename, when so I can tell I will return original result or the replaced one.
Thanks.
Zillions

**Comment by rk700** [comment]
Maybe `android.os.Process.myUid()`?

https://developer.android.com/reference/android/os/Process.html#myUid()

**Comment by zillions** [comment]
will give that a try, let you know the result.
right now I have another issue though, the hooking methods is working perfectly when I running the Demo.
but it seems this doesn't work in other app, I build another separate app just for testing, all the method seems haven't change, how can I make a hook, and make it work globally?
Thanks.

**Comment by zillions** [comment]
more info:
I changed a bit the demo, hooked some system method, most just check some system infos.
when I use the demo to check the result, all these infos are changed.
I made another app, only check the system info, but all these infos are original, which means the hook is not working on other app?
how can I get the hook working on third party apps, say like facebook?
Thanks.
Zillions
