### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by wjy000** [rk700/YAHFA#7]
我想hook系统属性调用的c语言方法,您的例子里面可以成功hook自定义的native方法,但是这个方法没有类名,无从下手,请帮忙指导一下,谢谢
__system_property_get("ro.serialno", a);

**Comment by rk700** [comment]
对native方法做hook，只需要在插件某处执行hook的c代码就行。可以把相关的hook代码放到`JNI_OnLoad`中，然后在插件的某个类的静态代码块中`System.loadLibrary()`加载这个so库就行，例如 https://github.com/rk700/ChangePhoneInfo/blob/master/app/src/main/java/lab/galaxy/yahfa/HookInfo.java

**Comment by 16368728** [comment]
请问，如果 ro.serialno 用 java apis 如何进行 hook？

**Comment by rk700** [comment]
用java做hook，就是通过反射修改android.os.Build类的相应字段
