### ISSUE TITLE
一件非常奇怪的事情，调用原方法异常

### ISSUE THREAD

**Issue by rozbo** [rk700/YAHFA#83]
```
10-27 19:15:16.895 7612-7612/lab.galaxy.yahfa.demoApp W/YAHFA: in Log.e(): origin, call Log.e()
      Has mic: 
    in String.startsWith(): foo, f
    CertStatus: 
10-27 19:15:16.896 7612-7612/lab.galaxy.yahfa.demoApp W/origin: foo startsWith f is false
```
显然，
- 这里第一个hook没有调用原来的方法去`Log.e`。  
- 第二处竟然返回了`false`

环境是N，我猜测原因可能是：
1. 源码中只对hook调用了`NewGlobalRef`而backup没有，会不会backup被回收了呢？不过按道理来讲，如果他被回收应该崩溃才对，但实际上没有崩溃。
2. 是不是直接替换掉cache和结构体不太行？

有些晕。。。

**Comment by rozbo** [comment]
update:已验证非`NewGlobalRef`的原因

**Comment by rozbo** [comment]
奇怪的很,出问题的手机是miui9基于android7.0开发的,我给刷成cm后能正常工作了.  
也不知道是小米miui系统的原因还是巧合.

**Comment by rozbo** [comment]
看来作者实在是忙，我就把解决问题的过程记录在这里吧，要是我能解决，算是造福后人，如果解决不了，权当抛砖引玉

**Comment by rozbo** [comment]
为了能够直观跟踪到代码的具体执行逻辑，我选择使用ida来进行动态调试，结果，令人震惊的事情发生了。我发现编译后，调用原方法的那句指令在最终的汇编指令里是不存在的，也就是说，莫名其妙的消失了？？？？？或是被优化掉了？

**Comment by rozbo** [comment]
经过多放调试，原因终于找到了。
先说结论，是被dex2oat优化掉了。
原因是dex2oat的过程是在加载dex的过程中，先执行dex2oat，而这个时候插件本身的代码非常简单。
```java
    public static boolean hook(String thiz, String prefix) {
        Log.w("YAHFA", "in String.startsWith(): "+thiz+", "+prefix);
        return backup(thiz, prefix);
    }

    public static boolean backup(String thiz, String prefix) {
        return false;
  }
```
这个时候，dex2oat在转换机器指令的时候，会直接将整个`backup`函数`inline`掉，直接返回个false。
这种情况下，就不会去调用`artmethod`对象，更不可能调用原方法了。

所以，之前的有关

> `backup`只是一个`placeholder`，实现甚至可以为空

这种说法是不够全面的。


完美的解决方案我还没找到，目前我是在`backup`里写上大量的无意义代码确保不会被`inline`掉，虽然不美观，但好歹是能用的。。。

**Comment by rk700** [comment]
内联优化与不同系统编译策略有关，相似问题可见https://github.com/rk700/YAHFA/issues/17

可以尝试在backup中添加try-catch block，这样好像不会被内联优化掉

**Comment by rozbo** [comment]
另外一个思路，hook `execv` 来强行修改`dex2oat`的参数，从而实现一致的内联策略，或者干脆就是禁止编译。

**Comment by rozbo** [comment]
没有办法，内联是为了性能，但是这也给开发带来了极大的不便，尤其是底层开发。比如c++都有`noinline`和`always_inline`的声明，单java好像没有找到。所以为了开发和调试方便，在debug版修改execv也是无奈之举。

**Comment by rk700** [comment]
hook execv是可以的，但需要再引入native hook的整套框架，坑会比较多

**Comment by Carlyle-Lee** [comment]
我使用的是master分支代码，作为lib 依赖，直接hook的。（不是使用的插件方式。）
在8.0 系统上，出现了原方法找不到的问题。
在API 21 上，Hook 【java.net.URL  openConnection 】 方法，方法直接被阻塞。 也不执行原来的方法。

**Comment by rk700** [comment]
在hook之前，是先通过反射得到目标方法的，所以如果方法找不到，可能是在反射时出错，可以跟进去看是怎么回事
