### ISSUE TITLE
Hooking ActivityThread#attach(boolean) failed in system_server process.

### ISSUE THREAD

**Issue by solohsu** [rk700/YAHFA#90]
2018-12-31 13:49:20.408 1363-1363/? E/YAHFA-Native: mmap failed, errno = 13
2018-12-31 13:49:20.408 1363-1363/? E/YAHFA-Native: cannot hook method

I am trying to hook method ActivityThread#attach(boolean), in normal app process everything is ok, but in system_server process, mmap failed with errno 13 (EACCES).

**Comment by solohsu** [comment]
I have solved this. It turns out the SELinux disallow executable memory usage, setting SELinux mode to permissive or allowing execmem for system_server should do the trick.
http://androidxref.com/8.1.0_r33/xref/system/sepolicy/private/system_server.te#755

**Comment by ov3rf1ow** [comment]
Hey, i am unable to find classes in system_server to hook, can you help me with it.
